kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: tls-cert-renewer
  labels:
    app: tls-cert-renewer
    version: v1
spec:
  selector:
    matchLabels:
      app: tls-cert-renewer
      version: v1
  template:
    spec:
      containers:
        - name: deployment
          image: ldoming/tls-certificate-renewer:1.0.0
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: <REPLACE>
            - name: AWS_ACCESS_KEY_ID
              value: <REPLACE>
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsKey
                  name: tls-cert-renewer
          command:
            - ./tls-cert-renewer.py
            - --bucket_name 
            - <BUCKET NAME>
            - --prefix
            - <PREFIX>
      automountServiceAccountToken: true
      serviceAccountName: tls-cert-renewer
    metadata:
      labels:
        app: tls-cert-renewer
        version: v1